# Generated by Django 3.1.7 on 2021-02-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_link',
            field=models.URLField(default='https://youtu.be/N6pDHehzNGc'),
        ),
    ]
